<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/sender.proto

namespace App\Grpc\Sender\GPBMetadata;

class Sender
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xFD\x03\x0A\x12proto/sender.proto\x12\x06sender\"9\x0A\x0CEmailRequest\x12\x0A\x0A\x02to\x18\x01 \x01(\x09\x12\x0F\x0A\x07subject\x18\x02 \x01(\x09\x12\x0C\x0A\x04body\x18\x03 \x01(\x09\"C\x0A\x0DEmailResponse\x12\x0F\x0A\x07success\x18\x01 \x01(\x08\x12\x12\x0A\x0Amessage_id\x18\x02 \x01(\x09\x12\x0D\x0A\x05error\x18\x03 \x01(\x09\"\x0F\x0A\x0DStatusRequest\"T\x0A\x0EStatusResponse\x12\x16\x0A\x0Eactive_workers\x18\x01 \x01(\x05\x12\x1A\x0A\x12messages_processed\x18\x02 \x01(\x03\x12\x0E\x0A\x06status\x18\x03 \x01(\x092\x8B\x01\x0A\x0DSenderService\x128\x0A\x09SendEmail\x12\x14.sender.EmailRequest\x1A\x15.sender.EmailResponse\x12@\x0A\x0FGetWorkerStatus\x12\x15.sender.StatusRequest\x1A\x16.sender.StatusResponseBbZ0github.com/user/go-sender/internal/grpcserver/pb\xCA\x02\x0FApp\\Grpc\\Sender\xE2\x02\x1BApp\\Grpc\\Sender\\GPBMetadatab\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

