<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/sender.proto

namespace App\Grpc\Sender;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Ответ со статусом воркера
 *
 * Generated from protobuf message <code>sender.StatusResponse</code>
 */
class StatusResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 active_workers = 1;</code>
     */
    protected $active_workers = 0;
    /**
     * Generated from protobuf field <code>int64 messages_processed = 2;</code>
     */
    protected $messages_processed = 0;
    /**
     * Generated from protobuf field <code>string status = 3;</code>
     */
    protected $status = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $active_workers
     *     @type int|string $messages_processed
     *     @type string $status
     * }
     */
    public function __construct($data = NULL) {
        \App\Grpc\Sender\GPBMetadata\Sender::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 active_workers = 1;</code>
     * @return int
     */
    public function getActiveWorkers()
    {
        return $this->active_workers;
    }

    /**
     * Generated from protobuf field <code>int32 active_workers = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setActiveWorkers($var)
    {
        GPBUtil::checkInt32($var);
        $this->active_workers = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 messages_processed = 2;</code>
     * @return int|string
     */
    public function getMessagesProcessed()
    {
        return $this->messages_processed;
    }

    /**
     * Generated from protobuf field <code>int64 messages_processed = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMessagesProcessed($var)
    {
        GPBUtil::checkInt64($var);
        $this->messages_processed = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string status = 3;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>string status = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->status = $var;

        return $this;
    }

}

