<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/sender.proto

namespace App\Grpc\Sender;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Запрос статуса (может быть пустым, но хорошая практика иметь сообщение)
 *
 * Generated from protobuf message <code>sender.StatusRequest</code>
 */
class StatusRequest extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \App\Grpc\Sender\GPBMetadata\Sender::initOnce();
        parent::__construct($data);
    }

}

