global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'go-sender'
    static_configs:
      - targets: ['go-sender:8080']

  - job_name: 'laravel'
    static_configs:
      - targets: ['web:80']
    metrics_path: '/api/metrics'
